import React, { useContext, useEffect, useState } from 'react'
import { ShopContext } from '../context/ShopContext'
import Title from './Title'
import ProductItem from './ProductItem'

const LatestCollection = () => {//mount this on Home page after Hero component

    //get products data using context api
    const {products}=useContext(ShopContext)
    // get 10 products from products state variable
    const [latestProducts,setLatestProducts]=useState([])

    //when ever this component is loaded, then from product data, we should load the 10 products from latest product state
    
    useEffect(()=>{
        setLatestProducts(products.slice(0,10))//using this, in latest product state we will get 10 products
    },[products])//will be executed once when component gets loaded(once products is updated)
// here product url is /product and its product id that is autogenerated in mongodb when we add products, we have products details and related products
    // console.log(products) //we will get the products data
    //we will use these data to display a latest collection section where we will display recently added products
  return (
    <div className='my-10'>
    <div className="text-center py-8 text-3xl">
        <Title text1={'LATEST'} text2={'COLLECTION'} />
        <p className='w-3/5 m-auto text-xs sm:text-sm md:text-base text-gray-600'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam dolores similique, voluptates cupiditate repellendus ad dolorum, blanditiis deleniti eos neque vitae voluptatibus consequatur sapiente enim reprehenderit a cum exercitationem quasi.</p>
    </div>

    {/* logic to display in the latest collection section, we can add the recently added 10 products  */}
    {/* Rendering Products */}
    <div className='grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 gap-y-6'>
      {
        latestProducts.map((item,index)=>(//getting individual item and index
          <ProductItem key={index} id={item._id} image={item.image} name={item.name} price={item.price}  />//we need to add id, image, name and price here, adding all prop values here which we have destructured in the ProductItem component
          //if we click on any product, we will be redirected to /products/:id page
        ))
      }
    </div>
    </div>
  )
}

export default LatestCollection